
select distinct title, M.YEAR, P.PERSONID from MOVGEN MG JOIN MOVIE M ON MG.MOVIEID = M.MOVIEID JOIN GENRE G ON MG.GENREID = G.GENREID  
				JOIN MOVIECHARACTER MC ON M.MOVIEID = MC.MOVIEID JOIN PERSON P ON MC.PERSONID = P.PERSONID
                WHERE M.MOVIEID = 101 ;
                

insert into movie values ('200','neuer film','2018','C');
delete from movie where movieid = 200;

select * from moviedb.movie where id = 1977;
select * from genre;
SELECT * FROM MOVIE_GENRE;
SELECT * FROM MOVIE;    
select * from moviecharacter;
SELECT * FROM PERSON;


Select Genre, title, year, CHARACTER, NAME from MOVIE_GENRE MG JOIN MOVIE M ON MG.MOVIEID = M.MOVIEID JOIN GENRE G ON MG.GENREID = G.GENREID 
JOIN MOVIECHARACTER MC ON M.MOVIEID = MC.MOVIEID JOIN PERSON P ON MC.PERSONID = P.PERSONID
WHERE M.MOVIEID = 1;


DROP TABLE GENRE1;
DROP TABLE MOVIE1;
DROP TABLE MOVIE1_GENRE1;
DROP TABLE PERSON1;
DROP TABLE MOVIECHARACTER;

/* CREATE GENRE */
create table Genre1(
    GenreID INT,
    Genre varchar(100),
    MOVIEID INT,
    CONSTRAINT PK_GENRE1 PRIMARY KEY(GENREID),
    CONSTRAINT FK_GENRE1 FOREIGN KEY (MOVIEID) REFERENCES MOVIE1(MOVIEID),
    CONSTRAINT UQ_GENRE1 UNIQUE(GENRE)
    );

/* CREATE MOBIE */
CREATE TABLE MOVIE1(
    MOVIEID  INT,
    TITLE VARCHAR(100),
    YEAR INT,
    TYPE CHAR,
    CONSTRAINT PK_MOVIE1 PRIMARY KEY (MOVIEID)
);

/* CREATE MOVIE_GENRE */
CREATE TABLE MOVIE1_GENRE1(
    MOVIEID INT,
    GENREID INT,
    CONSTRAINT PK_MOVIE1_GENRE1 PRIMARY KEY (MOVIEID, GENREID)
);

/* CREATE TABLE MOVIECHARACTER */
CREATE TABLE MOVIECHARACTER(
    MOVIECHARID INT,
    CHARACTER VARCHAR(100),
    ALIAS VARCHAR(100),
    POSITION INT,
    MOVIEID INT,
    PERSONID INT,
    CONSTRAINT PK_MOVIECHARACTER PRIMARY KEY(MOVIECHARID),
    CONSTRAINT FK1_MOVIECHARACTER FOREIGN KEY (MOVIEID) REFERENCES MOVIE1 (MOVIEID),
    CONSTRAINT FK2_MOVIECHARACTER FOREIGN KEY (PERSONID) REFERENCES PERSON1 (PERSONID)
);

/* CREATE PERSON */
CREATE TABLE PERSON1(
    PERSONID INT,
    NAME VARCHAR(100),
    SEX CHAR,
    CONSTRAINT PK_PERSON1 PRIMARY KEY (PERSONID),
    CONSTRAINT UQ_PERSON1 UNIQUE(NAME)
);